### ISSUE TITLE
TASK 2251 (different stages)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#176]
First of all the folders/files structure. Looks odd.
![image](https://user-images.githubusercontent.com/18144023/117536051-a4b95f80-b001-11eb-85e3-e91b28fc1815.png)

**Comment by ssfxate** [comment]
##Stage 10
Inside the .section-image block, add the image 'images/screen2.png', the class of this element must be 'image'.
Checks want to have './images/screen2.png' (with ./)

**Comment by ssfxate** [comment]
## Stage 11
Extra spaces in the path
The image of the first link should be 'images / appstore.svg', the second link should be 'images / googleplay.png'.

**Comment by amatiyko** [comment]
@ssfxate Yes, I have fixed the initial structure of the `images` folder. 
there should be only one `images` folder in the root of the task and all images should be there.

You can fix it bu your own or download the task after remove (don't forget to save the progress somewhere)

please let me know if you have any questions

**Comment by ssfxate** [comment]
Thanks, I've downloaded it again, 'cause there were different pictures in both folders with the same names `screen1.png`, `screen2.png`, `screen3.png`.

I wasn't sure about the correct instances.

**Comment by ssfxate** [comment]
The folders structure has been changed, but not the descriptions.
All stages are still the same.
Stage 11 for example.
![image](https://user-images.githubusercontent.com/18144023/117611842-e0bd0380-b16c-11eb-968d-27b7fbb74dec.png)

**Comment by amatiyko** [comment]
@ssfxate fixed. Please download tasks to see the changes
