### ISSUE TITLE
task1069, misleading requirements

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#28]
If the number exceeds 999.99T it becomes **1aa**, after 999.99aa goes 1ab.

Also, make sure to keep trailing zeroes. 5 * 1e12 should become **5.00T and not 5T.**

1aa is like 5T, nor 5.00T.

**Comment by ssfxate** [comment]
4. The function formatNumber should work properly for numbers less than **999T**
5. The function formatNumber should work properly for numbers less than **999az**
6. The function formatNumber should work properly for numbers larger than **1ba**
7. The function formatNumber **should not cut trailing zeros**

Numbers' examples in checks 4,5,6 are w/o zeroes.

**Comment by AgileNix** [comment]
The task description is misleading indeed. That's fixed now.

The requirements are ok, though.

Let me know if you have passed the tests.

**Comment by ssfxate** [comment]
So we can focus the issue to the check `7. The function formatNumber should not cut trailing zeros`. It has the FAILED status.
It's still not passing, even #29 has been fixed and passed.
The output of my code you can check in #29. The code isn't trailing zeros. It should pass though.

**Comment by ssfxate** [comment]
Works now.
